### PR TITLE
Add react/redux linters

### PR DESCRIPTION
**Pull request by principlebrothers**
## Complete milestone 2
In this pull request, I added linters to the project

[Link to API repository](https://github.com/principlebrothers/hello_rails)

### CODE REVIEW

**Review by rloterh — COMMENTED** [review]
Hi Ernest, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Kindly ensure that your project complies with the following standards:
- [ ] In the README file for the Rails API, add a link to your React app.
- [ ]  In the README file for the React App, add a link to your Rails API.
- [ ] When submitting for a review - use a link to the pull request in your Rails API.
- [ ] Kindly ensure to remove the Microverse template logo (Rails API). Optionally, you can replace it with your own logo if you have one.
- [ ] Your Pull Request description is invalid. Kindly elaborate further on your Pull Request description to reflect the actual changes you implemented on this project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by principlebrothers** [comment]
Thanks for the review @rloterh. I really appreciate

**Review by BenMukebo — CHANGES_REQUESTED** [review]
### Hi @principlebrothers,

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻
- Your Pull Request has a proper title and description. ✔️  
- No Linter errors :heavy_check_mark: 
- There is a `Greeting` component. ✔️
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_


- [ ] Great job so far, however i It will be great to the `App` component to have a route that leads to the `Greeting` component.. This is a major requirement  asked in the project description for this project to be approved. ⬇️ 

Screenshot from 2022-12-01 15-49-34

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by BenMukebo — APPROVED** [review]
<h1>Status: Approve  :champagne:  :+1: :confetti_ball: 

### **Hi @principlebrothers**, 

### **Congratulations! 🎉 Project Approved ✅**

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

### To Highlight :1st_place_medal: 
- Your Pull Request has a proper title and description. ✔️  
- No Linter errors :heavy_check_mark: 
- There is an `App` component with routes 👍🏻 
- There is a `Greeting` component 👍🏻 
- There is a store, an action, and a reducer that uses the url to the endpoint from the Rails API 👍🏻 
- The two apps work togehther, keep rocking :rocket: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers :clinking_glasses:  and Happy coding!!! :dancers:💻  

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
